<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'BurndownActionMenuEventListener' => 'src/BurndownActionMenuEventListener.php',
    'BurndownApplication' => 'src/BurndownApplication.php',
    'BurndownController' => 'src/BurndownController.php',
    'BurndownDataDate' => 'src/BurndownDataDate.php',
    'BurndownDataView' => 'src/BurndownDataView.php',
    'BurndownDataViewController' => 'src/BurndownDataViewController.php',
    'BurndownException' => 'src/BurndownException.php',
    'BurndownListController' => 'src/BurndownListController.php',
    'BurndownTestDataGenerator' => 'src/BurndownTestDataGenerator.php',
    'SprintConstants' => 'src/SprintConstants.php',
    'SprintEndDateField' => 'src/SprintEndDateField.php',
    'SprintProjectCustomField' => 'src/SprintProjectCustomField.php',
    'SprintReportBurndownView' => 'src/SprintReportBurndownView.php',
    'SprintReportController' => 'src/SprintReportController.php',
    'SprintStartDateField' => 'src/SprintStartDateField.php',


    'SprintReportOpenTasksView' => 'src/SprintReportOpenTasksView.php',
    'SprintStartDateField' => 'src/SprintStartDateField.php',
    'SprintTaskStoryPointsField' => 'src/SprintTaskStoryPointsField.php',
    'SprintView' => 'src/SprintView.php',
  ),
  'function' => array(),
  'xmap' => array(
    'BurndownActionMenuEventListener' => 'PhabricatorEventListener',
    'BurndownApplication' => 'PhabricatorApplication',
    'BurndownController' => 'PhabricatorController',
    'BurndownDataView' => 'SprintView',
    'BurndownDataViewController' => 'BurndownController',
    'BurndownException' => 'Exception',
    'BurndownListController' => 'BurndownController',
    'BurndownTestDataGenerator' => 'PhabricatorTestDataGenerator',
    'SprintConstants' => 'ManiphestConstants',
    'SprintStartDateField' => 'SprintProjectCustomField',
    'SprintConstants' => 'ManiphestConstants',
    'SprintStartDateField' => 'SprintProjectCustomField',
    'SprintEndDateField' => 'SprintProjectCustomField',
    'SprintProjectCustomField' => array(
      'PhabricatorProjectCustomField',
      'PhabricatorStandardCustomFieldInterface',
    ),
    'SprintReportController' => 'BurndownController',
    'SprintReportController' => 'ManiphestController',
    'SprintReportBurndownView' => 'SprintView',
    'SprintReportController' => 'BurndownController',
    'SprintReportOpenTasksView' => 'SprintView',
    'SprintTaskStoryPointsField' => array(
      'ManiphestCustomField',
      'PhabricatorStandardCustomFieldInterface',
    ),
    'SprintView' => 'AphrontView',
  ),
));
