<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(
    'behavior-board-data-pie.js' => 'a1302bf1',
    'behavior-c3-chart.js' => '4bd6b4ca',
    'behavior-c3-pie.js' => 'ae804fb1',
    'behavior-sprint-boards.js' => 'b2754b95',
    'c3.css' => '93642428',
    'c3.js' => '4b517cca',
    'd3.min.js' => '1595fbde',
    'phui-workboard-view.css' => '24307748',
  ),
  'symbols' => array(
    'c3' => '4b517cca',
    'c3-css' => '93642428',
    'd3' => '1595fbde',
    'javelin-behavior-c3-board-data-pie' => 'a1302bf1',
    'javelin-behavior-c3-chart' => '4bd6b4ca',
    'javelin-behavior-c3-pie' => 'ae804fb1',
    'javelin-behavior-sprint-boards' => 'b2754b95',
    'phui-workboard-view-css' => '24307748',
  ),
  'requires' => array(
    '4b517cca' => array(
      'd3',
    ),
  ),
  'packages' => array(),
);
