<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(
    'behavior-c3-chart.js' => '339d1b90',
    'c3.css' => '93642428',
    'c3.js' => '4b517cca',
    'd3.min.js' => '1595fbde',
  ),
  'symbols' => array(
    'c3' => '4b517cca',
    'c3-css' => '93642428',
    'd3' => '1595fbde',
    'javelin-behavior-c3-chart' => '339d1b90',
  ),
  'requires' => array(
    '4b517cca' => array(
      'd3',
    ),
  ),
  'packages' => array(),
);
