<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(
    'behavior-board-data-pie.js' => 'a1302bf1',
    'behavior-burndown-report-chart.js' => '631b0017',
    'behavior-c3-chart.js' => '4bd6b4ca',
    'behavior-c3-pie.js' => 'ae804fb1',
    'behavior-events-table.js' => '973ce37a',
    'behavior-sprint-boards.js' => 'b2754b95',
    'behavior-sprint-table.js' => '8c4a2d63',
    'behavior-tasks-table.js' => '7159f460',
    'c3.css' => '93642428',
    'c3.js' => '4b517cca',
    'd3.min.js' => '1595fbde',
    'dataTables.css' => '29c5914e',
    'images/Screenshot-1.png' => '5e39aaad',
    'images/sort_asc.png' => 'b2a41175',
    'images/sort_both.png' => '3d11ec92',
    'images/sort_desc.png' => '98623de6',
    'jquery-1.11.2.js' => '75fa3fcc',
    'jquery.dataTables.js' => 'faddf310',
    'phui-workboard-view.css' => '24307748',
    'sprint-report.css' => 'f6959ade',
  ),
  'symbols' => array(
    'c3' => '4b517cca',
    'c3-css' => '93642428',
    'd3' => '1595fbde',
    'dataTables' => 'faddf310',
    'dataTables-css' => '29c5914e',
    'javelin-behavior-burndown-report-chart' => '631b0017',
    'javelin-behavior-c3-board-data-pie' => 'a1302bf1',
    'javelin-behavior-c3-chart' => '4bd6b4ca',
    'javelin-behavior-c3-pie' => 'ae804fb1',
    'javelin-behavior-events-table' => '973ce37a',
    'javelin-behavior-sprint-boards' => 'b2754b95',
    'javelin-behavior-sprint-table' => '8c4a2d63',
    'javelin-behavior-tasks-table' => '7159f460',
    'jquery' => '75fa3fcc',
    'phui-workboard-view-css' => '24307748',
    'sprint-report-css' => 'f6959ade',
  ),
  'requires' => array(
    '4b517cca' => array(
      'd3',
    ),
    'faddf310' => array(
      'jquery',
    ),
  ),
  'packages' => array(),
);
