<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'BurndownActionMenuEventListener' => 'events/BurndownActionMenuEventListener.php',
    'BurndownApplication' => 'application/BurndownApplication.php',
    'BurndownController' => 'controller/BurndownController.php',
    'BurndownDataDate' => 'util/BurndownDataDate.php',
    'BurndownDataView' => 'view/BurndownDataView.php',
    'BurndownDataViewController' => 'controller/BurndownDataViewController.php',
    'BurndownException' => 'exception/BurndownException.php',
    'BurndownListController' => 'controller/BurndownListController.php',
    'BurndownTestDataGenerator' => '__tests__/BurndownTestDataGenerator.php',
    'CeleritySprintResources' => 'celerity/CeleritySprintResources.php',
    'OpenTasksView' => 'view/OpenTasksView.php',
    'ProjectOpenTasksView' => 'view/ProjectOpenTasksView.php',
    'SprintBeginDateField' => 'customfield/SprintBeginDateField.php',
    'SprintBuildStats' => 'storage/SprintBuildStats.php',
    'SprintConstants' => 'constants/SprintConstants.php',
    'SprintEndDateField' => 'customfield/SprintEndDateField.php',
    'SprintProjectCustomField' => 'customfield/SprintProjectCustomField.php',
    'SprintQuery' => 'query/SprintQuery.php',
    'SprintReportBurndownView' => 'view/SprintReportBurndownView.php',
    'SprintReportController' => 'controller/SprintReportController.php',
    'SprintReportOpenTasksView' => 'view/SprintReportOpenTasksView.php',
    'SprintTaskStoryPointsField' => 'customfield/SprintTaskStoryPointsField.php',
    'SprintTransaction' => 'storage/SprintTransaction.php',
    'SprintView' => 'view/SprintView.php',
    'UserOpenTasksView' => 'view/UserOpenTasksView.php',
    'ViewController' => 'controller/ViewController.php',
  ),
  'function' => array(),
  'xmap' => array(
    'BurndownActionMenuEventListener' => 'PhabricatorEventListener',
    'BurndownApplication' => 'PhabricatorApplication',
    'BurndownController' => 'PhabricatorController',
    'BurndownDataView' => 'SprintView',
    'BurndownDataViewController' => 'BurndownController',
    'BurndownException' => 'Exception',
    'BurndownListController' => 'BurndownController',
    'BurndownTestDataGenerator' => 'PhabricatorTestDataGenerator',
    'CeleritySprintResources' => 'CelerityResourcesOnDisk',
    'ProjectOpenTasksView' => 'OpenTasksView',
    'SprintBeginDateField' => 'SprintProjectCustomField',
    'SprintConstants' => 'ManiphestConstants',
    'SprintEndDateField' => 'SprintProjectCustomField',
    'SprintProjectCustomField' => array(
      'PhabricatorProjectCustomField',
      'PhabricatorStandardCustomFieldInterface',
    ),
    'SprintReportBurndownView' => 'SprintView',
    'SprintReportController' => 'BurndownController',
    'SprintReportOpenTasksView' => 'SprintView',
    'SprintTaskStoryPointsField' => array(
      'ManiphestCustomField',
      'PhabricatorStandardCustomFieldInterface',
    ),
    'SprintView' => 'AphrontView',
    'UserOpenTasksView' => 'OpenTasksView',
  ),
));
